
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhjoxjeptfvndwzoawhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhoam94amVwdGZ2bmR3em9hd2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjg3NzAsImV4cCI6MjA2MjgwNDc3MH0.d4n0gCEIMUocIeuuDR2pHNhWA76IAKX_HhG2sh-DQYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
